name       : synergy
version    : 1.6.3
release    : 1
source     :
    - https://github.com/synergy/synergy/archive/1.6.3.tar.gz : 93b1965b8e0cfc55cc654aab7053a58b9e730d09e68bbc520be32353a01dce1a
license    : GPL-2.0
builddeps  :
    - pkgconfig(x11)
    - pkgconfig(xtst)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(Qt5Core)
    - pkgconfig(egl)
    - pkgconfig(avahi-core)
#unzip is to fix this issue: https://github.com/synergy/synergy/issues/4368 see setup section for more nasty fixes
    - unzip
summary    : Share one mouse and keyboard between multiple computers on your desk
clang      : no
description: |
    Share one mouse and keyboard between multiple computers on your desk
setup      : |
    mkdir -p ext/gmock-1.6.0 ext/gtest-1.6.0 ext/cryptopp562
    mv ext/gmock-1.6.0.zip ext/gmock-1.6.0/
    mv ext/gtest-1.6.0.zip ext/gtest-1.6.0/
    mv ext/cryptopp562.zip ext/cryptopp562/
    cd ext/gmock-1.6.0/
    unzip gmock-1.6.0.zip
    cd ../gtest-1.6.0/
    unzip gtest-1.6.0.zip
    cd ../cryptopp562/
    unzip cryptopp562.zip
    cd ../..
build      : |
    ./hm.sh conf -g1
    ./hm.sh build
install    : |
    install -Dm755 bin/synergy "%installroot%/usr/bin/synergy"
    install -Dm755 bin/synergyc "%installroot%/usr/bin/synergyc"
    install -Dm755 bin/synergys "%installroot%/usr/bin/synergys"
