name       : synergy
version    : 1.10.1
release    : 12
source     :
    - https://github.com/symless/synergy-core/archive/v1.10.1-stable.tar.gz : 67ef37a9c090e0197018220c04df3005fc574a391935c29b7cb0c3f208fd0429
license    : GPL-2.0-or-later
component  : network.utils
summary    : Share one mouse and keyboard between multiple computers on your desk
description: |
    Share one mouse and keyboard between multiple computers on your desk
builddeps  :
    - pkgconfig(avahi-core)
    - pkgconfig(egl)
    - pkgconfig(libcurl)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - pkgconfig(xinerama)
    - pkgconfig(xtst)
    - pkgconfig(xrandr)
setup      : |
    %patch -p1 < $pkgfiles/qt5_fix.patch
    %cmake .
build      : |
    %make
install    : |
    install -Dm00755 bin/synergy $installdir/usr/bin/synergy
    install -Dm00755 bin/synergyc $installdir/usr/bin/synergyc
    install -Dm00755 bin/synergys $installdir/usr/bin/synergys
    install -Dm00755 bin/syntool $installdir/usr/bin/syntool
    install -Dm00644 res/synergy.ico $installdir/usr/share/icons/synergy.ico
    install -Dm00644 res/synergy.desktop $installdir/usr/share/applications/synergy.desktop
