name       : synergy
version    : 1.7.6
release    : 3
source     :
    - https://github.com/symless/synergy/archive/v1.7.6-stable.tar.gz : a453b880606edbdaec82576bcb74189a7ae564feeee126b125063802a778411d
license    : GPL-2.0
builddeps  :
    - pkgconfig(avahi-core)
    - pkgconfig(egl)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - pkgconfig(xinerama)
    - pkgconfig(xtst)
    - pkgconfig(xrandr)
#unzip is to fix this issue: https://github.com/synergy/synergy/issues/4368 see setup section for more nasty fixes
    - unzip
summary    : Share one mouse and keyboard between multiple computers on your desk
clang      : no
description: |
    Share one mouse and keyboard between multiple computers on your desk
setup      : |
    mkdir -p ext/gmock-1.6.0 ext/gtest-1.6.0
    mv ext/gmock-1.6.0.zip ext/gmock-1.6.0/
    mv ext/gtest-1.6.0.zip ext/gtest-1.6.0/
    cd ext/gmock-1.6.0/
    unzip gmock-1.6.0.zip
    cd ../gtest-1.6.0/
    unzip gtest-1.6.0.zip
    cd ../..
build      : |
    ./hm.sh conf -g1
    ./hm.sh build
install    : |
    install -Dm755 bin/synergy "%installroot%/usr/bin/synergy"
    install -Dm755 bin/synergyc "%installroot%/usr/bin/synergyc"
    install -Dm755 bin/synergys "%installroot%/usr/bin/synergys"
    install -Dm755 bin/syntool "%installroot%/usr/bin/syntool"
    install -D -m 00644 res/synergy.ico $installdir/usr/share/icons/synergy.ico
    install -D -m 00644 res/synergy.desktop $installdir/usr/share/applications/synergy.desktop
