name       : synergy
version    : 1.8.6
release    : 9
source     :
    - https://github.com/symless/synergy/archive/v1.8.6-stable.tar.gz : 76b27c6e90961ee6bdad429904a2d5743854d0d027c067941d2411565d64352b
license    : GPL-2.0
component  : network.utils
summary    : Share one mouse and keyboard between multiple computers on your desk
description: |
    Share one mouse and keyboard between multiple computers on your desk
builddeps  :
    - pkgconfig(avahi-core)
    - pkgconfig(egl)
    - pkgconfig(libcurl)
    - pkgconfig(Qt5Core)
    - pkgconfig(x11)
    - pkgconfig(xinerama)
    - pkgconfig(xtst)
    - pkgconfig(xrandr)
#unzip is to fix this issue: https://github.com/symless/synergy/issues/4368 see setup section for more nasty fixes
    - unzip
setup      : |
    mkdir -p ext/gmock-1.6.0 ext/gtest-1.6.0
    unzip ext/gmock-1.6.0.zip -d ext/gmock-1.6.0
    unzip ext/gtest-1.6.0.zip -d ext/gtest-1.6.0
build      : |
    %cmake .
    %make
    cd src/gui
    qmake
    %make
install    : |
    install -Dm755 bin/synergy $installdir/usr/bin/synergy
    install -Dm755 bin/synergyc $installdir/usr/bin/synergyc
    install -Dm755 bin/synergys $installdir/usr/bin/synergys
    install -Dm755 bin/syntool $installdir/usr/bin/syntool
    install -D -m 00644 res/synergy.ico $installdir/usr/share/icons/synergy.ico
    install -D -m 00644 res/synergy.desktop $installdir/usr/share/applications/synergy.desktop
