name       : synergy
version    : 1.12.0
release    : 15
source     :
    - git|https://github.com/symless/synergy-core.git : v1.12.0-stable
license    : GPL-2.0-or-later
component  : network.utils
summary    : Share one mouse and keyboard between multiple computers on your desk
description: |
    Share one mouse and keyboard between multiple computers on your desk
networking : yes
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(avahi-core)
    - pkgconfig(gtest)
    - pkgconfig(libcurl)
    - pkgconfig(x11)
    - pkgconfig(xinerama)
    - pkgconfig(xrandr)
    - pkgconfig(xtst)
setup      : |
    %patch -p1 < $pkgfiles/qt5_fix.patch
    # Remove tests that require X
    rm src/test/integtests/platform/XWindowsScreenTests.cpp
    rm src/test/integtests/platform/XWindowsKeyStateTests.cpp
    %cmake .
build      : |
    %make
install    : |
    install -Dm00755 bin/synergy $installdir/usr/bin/synergy
    install -Dm00755 bin/synergyc $installdir/usr/bin/synergyc
    install -Dm00755 bin/synergys $installdir/usr/bin/synergys
    install -Dm00755 bin/syntool $installdir/usr/bin/syntool
    install -Dm00644 res/synergy.ico $installdir/usr/share/icons/synergy.ico
    install -Dm00644 res/synergy.desktop $installdir/usr/share/applications/synergy.desktop
check      : |
    ./bin/unittests
    ./bin/integtests

